# Generated by Django 4.2.13 on 2024-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='educationalresources',
        #     name='exercises',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='educationalresources',
        #     name='hours',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='educationalresources',
        #     name='lessons',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='educationalresources',
        #     name='projects',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='educationalresources',
        #     name='skills',
        #     field=models.CharField(max_length=255),
        # ),
    ]
