# Generated by Django 4.2.13 on 2024-07-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0002_alter_educationalresources_exercises_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='educationalresources',
        #     name='exercises',
        # ),
    ]
