# Generated by Django 4.2.13 on 2024-07-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0003_remove_educationalresources_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalresources',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='educationalresources',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='educationalresources',
            name='level',
        ),
        migrations.RemoveField(
            model_name='educationalresources',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='educationalresources',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='educationalresources',
            name='title',
        ),
    ]
