# Generated by Django 4.2.13 on 2024-07-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0004_remove_educationalresources_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalresources',
            name='exercises',
        ),
    ]
