# Generated by Django 4.2.13 on 2024-08-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0005_remove_educationalresources_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresources',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalresources',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/'),
        ),
    ]
